routes/web.php
<?php

Route::get('login', function() {
    return redirect()->route('home');
})->name('login');

Route::get('/', 'HomeController@index')->name('home');

Route::get('lang/{locale?}', [
    'as' => 'home',
    'uses' => 'HomeController@changeLang'
]);

Route::get('/privacy', 'HomeController@privacy')->name('privacy');

Route::get('login/{driver}', 'LoginController@redirectToProvider');
Route::get('login/{driver}/callback', 'LoginController@handleProviderCallback');
Route::get('logout', 'LoginController@logout');

Route::post('save/{key}', 'SaveController@store');
Route::get('read/{private_key}/rss', 'ReadController@readRss')->name('read.rss');
Route::get('read/{private_key}/json', 'ReadController@readJson')->name('read.json');
Route::get('read/{private_key}/csv', 'ReadController@readCsv')->name('read.csv');

Route::resource('keys', 'KeysController');
Route::resource('entries', 'EntriesController');

app/Entry.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Entry extends Model
{
    public function key()
    {
        return $this->belongsTo('App\Key');
    }

    public function getObjectContentsAttribute()
    {
        return json_decode($this->contents);
    }

    public function getPrettyContentsAttribute()
    {
        return json_encode($this->object_contents, JSON_PRETTY_PRINT);
    }
}

app/Key.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Key extends Model
{
    public function entries()
    {
        return $this->hasMany('App\Entry')->orderBy('created_at', 'desc');
    }

    public function getPrintableNameAttribute()
    {
        if (empty($this->name))
            return $this->key;
        else
            return $this->name;
    }

    public function getPostEndpointAttribute()
    {
        return url('/save/' . $this->key);
    }

    public function getRssFeedAttribute()
    {
        return route('read.rss', $this->private_key);
    }

    public function getJsonFeedAttribute()
    {
        return route('read.json', $this->private_key);
    }

    public function getCsvFeedAttribute()
    {
        return route('read.csv', $this->private_key);
    }
}

resources/views/dashboard.blade.php
@extends('layouts.public')

@section('contents')

<section class="main-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
                    @foreach($keys as $index => $key)
                        <a class="nav-link {{ $index == 0 ? 'active' : '' }}" data-toggle="pill" href="#key_{{ $key->id }}" role="tab">{{ $key->printable_name }}</a>
                    @endforeach
                    <a href="#" class="nav-link" data-toggle="modal" data-target="#newKey">{{ _i('Crea Nuova Chiave') }}</a>
                </div>
            </div>
            <div class="col-md-9">
                <div class="tab-content">
                    @foreach($keys as $index => $key)
                        <div class="tab-pane fade {{ $index == 0 ? 'show active' : '' }}" id="key_{{ $key->id }}" role="tabpanel">
                            @include('key', ['key' => $key])
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</section>

<div class="modal fade" id="newKey" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{{ _i('Crea Nuova Chiave') }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="{{ _i('Annulla') }}">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" action="{{ url('keys') }}">
                <div class="modal-body">
                    {!! csrf_field() !!}

                    <div class="row">
                        <div class="col">
                            <div class="form-group row">
                                <label for="name" class="col-sm-3 col-form-label">{{ _i('Nome') }}</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" name="name">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ _i('Annulla') }}</button>
                    <button type="submit" class="btn btn-primary">{{ _i('Salva') }}</button>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

resources/views/home.blade.php
@extends('layouts.public')

@section('contents')

<section class="header-wrapper text-center">
    <div>
        <img class="img-fluid" src="{{ url('/images/logo.png') }}">
        <h3>{{ _i('Raccogli dati dai tuoi utenti') }}<br>{{ _i('senza server e senza pensieri.') }}</h3>
        <br><br>
        <a href="#usage-wrapper" class="btn btn-success btn-lg">{{ _i('Provalo!') }}</a>
    </div>
</section>

<section class="features-wrapper">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card-deck">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title text-center"><i class="fa fa-clipboard fa-3x" aria-hidden="true"></i></h4>
                            <p class="card-text">{{ _i('Copia e incolla un URL nella tua pagina web, e sei subito operativo.') }}</p>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title text-center"><i class="fa fa-bullhorn fa-3x" aria-hidden="true"></i></h4>
                            <p class="card-text">{{ _i('RSS, JSON e CSV: molteplici canali di notifica dei dati caricati.') }}</p>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title text-center"><i class="fa fa-server fa-3x" aria-hidden="true"></i></h4>
                            <p class="card-text">{{ _i('Usalo gratuitamente, oppure scaricalo ed installalo su un tuo server personale.') }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- FAQ -->

<section class="questions-wrapper">
    <div class="container">
        <div class="row">
            <div class="col lead">
                <p>
                    {!! _i("Con <strong>Postegg</strong> puoi raccogliere i dati immessi dai tuoi utenti in qualsiasi form online, senza doverli direttamente processare con una applicazione o salvare su un database. Puoi usarlo per un form di contatto, un sondaggio o la registrazione ad una newsletter, su un qualsiasi sito statico in HTML.") !!}
                </p>
                <p>
                    {!! _i("Per usarlo, basta registrarsi e definire alcuni parametri per ottenere una API key da usare direttamente nella <code>action</code> dei tuoi form, ad esempio:") !!}
                </p>
                <p>
                    <pre>&lt;form method="POST" action="{{ env('APP_URL') }}/save/{{ _i('LA_TUA_API_KEY') }}"&gt;
    &lt;input type="text" name="name" placeholder="{{ _i('Il Tuo Nome') }}"&gt;&lt;br&gt;
    &lt;input type="email" name="email" placeholder="{{ _i('La Tua EMail') }}"&gt;&lt;br&gt;
    &lt;button type="submit">{{ _i('Invia') }}&lt;/button&gt;
&lt;/form&gt;</pre>
                </p>
                <p>
                    {{ _i("I dati raccolti saranno esposti per mezzo di un feed RSS ed una API JSON, accessibili con un'altra API key, privata.") }}
                </p>
            </div>
        </div>
    </div>
</section>

<!-- UTILIZZO -->

<section class="usage-wrapper" id="usage-wrapper">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card-group">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title text-left">{{ _i('Accedi...') }}</h4>
                            <p class="card-text">
                                {{ _i('Usa direttamente questo servizio.') }}
                            </p>
                            <p>
                                {{ _i('Attenzione: questa istanza, pubblica e gratuita, ha alcune limitazioni:') }}
                            </p>
                            <ul>
                                <li>{{ _i('vengono conservate al più %d immissioni per account. Oltre questo limite, le più vecchie vengono cancellate', [env('MAX_SUBMISSION_COUNT')]) }}</li>
                                <li>{{ _i('non vengono salvate immissioni con più di %d caratteri', [env('MAX_SUBMISSION_LENGTH')]) }}</li>
                                <li>{{ _i('non vengono salvate più di 10 immissioni al minuto') }}</li>
                            </ul>
                        </div>
                        <div class="card-footer text-center">
                            <span class="align-middle">
                                @if(!empty(env('GITHUB_CLIENT_ID')))
                                    <a class="btn btn-success" href="{{ url('login/github') }}">{{ _i('Login con GitHub') }}</a>
                                @endif
                                @if(!empty(env('GITLAB_KEY')))
                                    <a class="btn btn-success" href="{{ url('login/gitlab') }}">{{ _i('Login con GitLab') }}</a>
                                @endif
                            </span>
                        </div>
                    </div>

                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title text-right">{{ _i('... oppure scarica ed installa') }}</h4>
                            <p class="card-text">
                                {{ _i("Per una gestione totalmente personalizzata dell'applicazione e dei dati raccolti, scarica gratuitamente Postegg ed installalo sul tuo server o sul tuo spazio hosting.") }}
                            </p>
                        </div>
                        <div class="card-footer text-center">
                            <span class="align-middle">
                                <a class="btn btn-success" href="https://gitlab.com/madbob/postegg">{{ _i('Vedi il Codice') }}</a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@endsection

resources/views/key.blade.php
<form method="POST" action="{{ route('keys.update', ['id' => $key->id]) }}">
    {!! csrf_field() !!}
    {{ method_field('PUT') }}

    <div class="row">
        <div class="col">
            <div class="form-group row">
                <label for="name" class="col-sm-3 col-form-label">{{ _i('Nome') }}</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="name" value="{{ $key->name }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="redirect" class="col-sm-3 col-form-label">{{ _i('Redirect') }}</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="redirect_url" value="{{ $key->redirect_url }}">
                    <small class="form-text text-muted">
                        {{ _i("URL dove redirigere l'utente dopo il salvataggio dei dati") }}
                    </small>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-3 col-form-label">{{ _i('POST endpoint') }}</label>
                <div class="col-sm-9">
                    <input type="text" readonly class="form-control" value="{{ $key->post_endpoint }}">
                    <small class="form-text text-muted">
                        {!! _i('Adopera questo URL come <code>action</code> del tuo form') !!}
                    </small>
                </div>
            </div>

            <hr>

            <div class="form-group row">
                <label for="rss" class="col-sm-3 col-form-label">{{ _i('Feed RSS') }}</label>
                <div class="col-sm-9">
                    <input type="text" readonly class="form-control" value="{{ $key->rss_feed }}">
                    <small class="form-text text-muted">
                        {{ _i('Include le ultime 15 immissioni') }}
                    </small>
                </div>
            </div>
            <div class="form-group row">
                <label for="json" class="col-sm-3 col-form-label">{{ _i('Feed JSON') }}</label>
                <div class="col-sm-9">
                    <input type="text" readonly class="form-control" value="{{ $key->json_feed }}">
                    <small class="form-text text-muted">
                        {{ _i('Include tutte le immissioni (le ultime %s)', [env('MAX_SUBMISSION_COUNT')]) }}
                    </small>
                </div>
            </div>
            <div class="form-group row">
                <label for="csv" class="col-sm-3 col-form-label">{{ _i('Feed CSV') }}</label>
                <div class="col-sm-9">
                    <input type="text" readonly class="form-control" value="{{ $key->csv_feed }}">
                    <small class="form-text text-muted">
                        {{ _i('Include tutte le immissioni (le ultime %s)', [env('MAX_SUBMISSION_COUNT')]) }}
                    </small>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-12">
                    <button type="submit" class="btn btn-primary pull-right">{{ _i('Salva') }}</button>
                </div>
            </div>
        </div>
    </div>
</form>

<div class="row">
    <div class="col entries">
        @if($key->entries->count() == 0)
            <div class="alert alert-info">
                {{ _i('I dati saranno visualizzati qui, quando ce ne saranno.') }}
            </div>
        @else
            @foreach($key->entries as $entry)
                <hr>

                <div>
                    <a href="#" data-entry-id="{{ $entry->id }}" class="btn btn-danger pull-right entry-delete">
                        <i class="fa fa-remove"></i>
                    </a>

                    <h4>{{ $entry->created_at }} / {{ $entry->ip }}</h4>
                    <pre>{{ $entry->pretty_contents }}</pre>
                </div>

            @endforeach
        @endif
    </div>
</div>

resources/views/privacy.blade.php
@extends('layouts.public')

@section('contents')

<section class="minor-header-wrapper text-center">
    <div>
        <img class="img-fluid" src="{{ url('/images/logo.png') }}">
    </div>
</section>

<section class="privacy-wrapper">
    <div class="container">
        <div class="row">
            <div class="col">
                <p>
                    {{ _i('I dati non vengono condivisi con nessuno esterno alla piattaforma, se non in forma aggregata e non riconducibile a nessuna persona.') }}
                </p>
                <p>
                    {{ _i("Gli utenti registrati possono accedere alle informazioni di loro pertinenza qui salvate da soggetti terzi per mezzo del servizio pubblico, compresi la data di salvataggio e l'indirizzo IP.") }}
                </p>
                <p>
                    {{ _i('Vengono usati solo cookie "tecnici" di autenticazione.') }}
                </p>
                <p>
                    {!! _i('Il server sta in Germania, presso <a href="https://www.hetzner.com/">questo provider qui</a>.') !!}
                </p>
                <p>
                    {{ _i("Non sono responsabile per nessun dato o informazione sulla piattaforma. Né tantomeno della loro perdita, modifica, cancellazione, e per qualsiasi cosa possa succedere a loro e a causa del loro utilizzo.") }}
                </p>
                <p>
                    {!! _i('Per eliminare un account, e tutti i dati relativi, mandatemi una mail all\'indirizzo <a href="mailto:info@madbob.org">info@madbob.org</a>. Il tutto verrà cancellato entro 12 mesi.') !!}
                </p>
            </div>
        </div>
    </div>
</section>

@endsection